# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CTbZmKtBzJ3k81L0MH5p2UGEXx1eBjwc
"""

import re
def add(numbers):
    if numbers == '':
        return 0
    else:
        numbers = map(int, re.findall(r"-?\d+", numbers))
        numbers = list(filter(lambda x: x < 1000, numbers))
        negative_numbers = list(filter(lambda x: x < 0, numbers))
        try:
          if negative_numbers: raise Exception('negatives not allowed ' + str(negative_numbers))
        except:
          print('negatives not allowed ' + str(negative_numbers))
        return sum(numbers)
add("1,2:")

add("-1,4")

add("2)*09")